<HTML>
<HEAD>
<TITLE>Moved Permanently</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Permanently</H1>
The document has moved <A HREF="https://raw.githubusercontent.com/express42/otus-snippets/f15d933e64369a4ef52ba0ef5f0942942efd38d5/play-travis/.travis.yml">here</A>.
</BODY>
</HTML>
